repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: prettier
        name: format
        language: node
        entry: prettier --write
        types_or: [javascript, ts]
        additional_dependencies:
          - 'prettier@^3.3.3'

      - id: eslint
        name: lint
        language: node
        entry: npx eslint
        types_or: [javascript, ts]
        additional_dependencies:
          - 'eslint@^9.30.1'
          - 'typescript-eslint@^8.35.1'

      - id: tsc
        name: type check
        language: node
        entry: tsc --noEmit -p ./
        pass_filenames: false
        types_or: [javascript, ts]
        additional_dependencies:
          - 'typescript@^4.6.4'

      - id: check-license-headers
        name: check license headers
        language: python
        entry: python ./utils/license.py
