name: Build extension

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build extension
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: ./.github/actions/setup

      - name: Bundle TypeScript
        run: npm run bundle

      - name: Package extension
        run: npm run package

      - name: Upload extension as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: extension-${{ github.sha }}
          path: ./out/vscode-mojo.vsix
          retention-days: 14
