name: Build and deploy extension

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Publish to marketplaces.
        type: boolean
        default: true

  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  publish:
    name: Publish extension
    runs-on: ubuntu-latest
    needs: [build]

    defaults:
      run:
        shell: bash

    steps:
      - name: Setup Node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
        with:
          node-version: 20

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install dependencies
        run: npm run ci

      - name: Upload extension to VS Code marketplace
        if: ${{ inputs.publish }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish --packagePath ${{ needs.build.outputs.vsix }}

      - name: Upload extension to Open-VSX marketplace
        if: ${{ inputs.publish }}
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
        run: npx ovsx publish ${{ needs.build.outputs.vsix }}
