name: Lint extension

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        shell: bash

    steps:
      - uses: ./.github/actions/setup

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run eslint
        run: npx eslint

      - name: Check TypeScript
        run: npm run typecheck
