name: Test extension

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: ./.github/actions/setup

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@273e4808c831936a3ce1a3080c829d9e153143d3
        with:
          pixi-version: v0.49.0
          run-install: false

      - name: Initialize Pixi workspace
        working-directory: fixtures/pixi-workspace
        run: pixi install --locked

      - name: Build extension
        run: npm run build

      - name: Execute tests
        run: xvfb-run -a npm test
